---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	generate_joke(generate_joke)
	improve_joke(improve_joke)
	polish_joke(polish_joke)
	__end__([<p>__end__</p>]):::last
	__start__ --> generate_joke;
	generate_joke -. &nbsp;Pass&nbsp; .-> __end__;
	generate_joke -. &nbsp;Fail&nbsp; .-> improve_joke;
	improve_joke --> polish_joke;
	polish_joke --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
